# Generated by Django 5.1.3 on 2024-11-22 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inundacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField()),
                ("anio", models.IntegerField()),
                ("full_text", models.TextField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
