# Generated by Django 5.1.3 on 2024-11-23 04:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inundaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaInundaciones",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("anio", models.IntegerField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "vista_inundaciones_combinada",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Colonia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("pobtotal", models.IntegerField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
            ],
        ),
    ]
